### ISSUE TITLE
Exception when I try to create a Dataframe from source data

### ISSUE THREAD

**Issue by alonsoir** [diana-hep/spark-root#21]
Hi, When I try to load the Dataframes with the example files, I got an exception. I have tried to use the last two versions of the library, 0.15 and 0.16 and in both the exceptions occur.

I am attaching a file with the output.
[issue-spark-shell-diana-hep.txt](https://github.com/diana-hep/spark-root/files/3152497/issue-spark-shell-diana-hep.txt)

**Comment by vkhristenko** [comment]
hey, thanks for reporting. this package is not being maintained anymore.

but to solve your particular problem, use this jar: https://github.com/diana-hep/spark-root/tree/master/jars

just start it as `spark-shell --packages org.diana-hep:root4j:<whichever is the latest>` --jars spark-root_2.11-0.1.17.jar

**Comment by alonsoir** [comment]
Ok, thank you sir. Attaching the file with the success loading the files into DataFrames.
 
[issue-spark-shell-diana-hep.txt](https://github.com/diana-hep/spark-root/files/3152738/issue-spark-shell-diana-hep.txt)
