### ISSUE TITLE
Is there a maintained version?

### ISSUE THREAD

**Issue by alonsoir** [diana-hep/spark-root#22]
I can use the library using root4j, I can load Dataframes and work with them, but, the library is no longer maintained, so, is there any maintained library?

[issue-spark-shell-diana-hep.txt](https://github.com/diana-hep/spark-root/files/3152837/issue-spark-shell-diana-hep.txt)

**Comment by vkhristenko** [comment]
this guy is actively maintained https://github.com/scikit-hep/uproot

VK

**Comment by alonsoir** [comment]
But only python? Well, at least we have yours for the java/scale people.
Thank you Victor

**Comment by vkhristenko** [comment]
yep in there it's just python. np Alonso

**Comment by reikdas** [comment]
I am not sure if this is the sort of thing you are looking for, but you can take a look at this - https://github.com/PerilousApricot/spark-ttree (It is still being developed though I think)
