### ISSUE TITLE
Regarding public CMS MuOnia Example Analysis python notebook

### ISSUE THREAD

**Issue by renato2099** [diana-hep/spark-root#24]
Hi everyone,

I was wondering if the notebook provided as an example ([publicCMSMuonia_exampleAnalysis](https://github.com/diana-hep/spark-root/blob/master/ipynb/publicCMSMuonia_exampleAnalysis_wROOT.ipynb)) was the actual code/workflow run here or at least similar in functionality [here](https://www.epj-conferences.org/articles/epjconf/pdf/2019/19/epjconf_chep2018_06030.pdf) and [here](http://canali.web.cern.ch/canali/docs/Big_Data_HEP_Analysis_and_ML_with_Spark_20190924.pdf)
Thanks in advanced for any pointers!

**Comment by vkhristenko** [comment]
hey, yep, all the notebooks are the actual code. this project is no longer maintained, but all notebooks/etc should work, provided the requirements are satisfied. Just to add, that these notebooks might have older versions of spark-root/root4j.

I would suggest to use something like [uproot](https://github.com/scikit-hep/uproot)

**Comment by renato2099** [comment]
hey @vkhristenko,
Thanks a lot for replying back! Those are very cool numbers for the scalability tests 👍
I was wondering about the actual hw where the scalability tests where run. The paper states: 

> This infrastructure is comprised of almost 1300 cores and 7TB of RAM. 

But the slides show three different clusters (1) Hadoop Yarn with 30 nodes with 13TB of RAM, (2) Hadoop Yarn with 65 nodes with 20TB of RAM, (3) Kubernetes 250 cores with 2TB of RAM. So none of these match the ones mentioned in the paper. Would you be able to tell which actual cluster was used? and maybe the actual hw specs of the machines?
Many thanks in advance @vkhristenko !

**Comment by vkhristenko** [comment]
@renato2099, sorry for the actual hw specs i'm not the right guy to ask

May be @LucaCanali can provide more info in terms of machine specs.

**Comment by LucaCanali** [comment]
@renato2099 we have been running the data reduction workload at scale on various systems (production and test), also over time the clusters have evolved as new nodes are being added, old machine are decommisioned. For the actual tests reported in the article the number of cores and memory used at the time (on a shared YARN system) are repoted with the performance graphs. YOu can direct mail me if you need more info.

**Comment by renato2099** [comment]
Thanks @vkhristenko and @LucaCanali  for your support!
